package com.github.eciuca.awssdk.dynamodb;

import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeReflection;

import software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider;
import software.amazon.awssdk.enhanced.dynamodb.internal.extensions.AutoGeneratedTimestampRecordAttributeTags;
import software.amazon.awssdk.enhanced.dynamodb.internal.extensions.AutoGeneratedUuidTag;
import software.amazon.awssdk.enhanced.dynamodb.internal.extensions.VersionRecordAttributeTags;
import software.amazon.awssdk.enhanced.dynamodb.internal.mapper.BeanTableSchemaAttributeTags;

public class DynamoDbEnhancedNativeImageSubstitutions implements Feature {
    @Override
    public void beforeAnalysis(BeforeAnalysisAccess access) {
        try {
            RuntimeReflection.register(DefaultAttributeConverterProvider.class.getConstructor());
            RuntimeReflection.register(BeanTableSchemaAttributeTags.class);
            RuntimeReflection.register(BeanTableSchemaAttributeTags.class.getMethods());
            RuntimeReflection.register(AutoGeneratedUuidTag.class);
            RuntimeReflection.register(AutoGeneratedUuidTag.class.getMethods());
            RuntimeReflection.register(AutoGeneratedTimestampRecordAttributeTags.class);
            RuntimeReflection.register(AutoGeneratedTimestampRecordAttributeTags.class.getMethods());
            RuntimeReflection.register(VersionRecordAttributeTags.class);
            RuntimeReflection.register(VersionRecordAttributeTags.class.getMethods());
        } catch (NoSuchMethodException ex) {
            throw new IllegalStateException(
                    "SVM Substitution: Unable to register method for reflection", ex);
        }
    }
}
